ARDUINO_DIR=/usr/share/arduino
BOARD_TAG=uno
ARDUINO_PORT=/dev/ttyACM*
ARDUINO_LIBS=IRremote rover Ultrasonic
USER_LIB_PATH=../../libraries
include /usr/share/arduino/Arduino.mk
include $(USER_LIB_PATH)/testing/testing.mk
